$buckets = @(
    'extras'
    'nerd-fonts'
    'versions'
)
$packages = @(
    'extras/kdeconnect'
    'extras/lazygit'
    'extras/nsis'
    'extras/vcredist2022'
    'extras/vscode'
    'main/7zip'
    'main/btop'
    'main/composer'
    'main/eza'
    'main/fd'
    'main/ffmpeg'
    'main/fzf'
    'main/gh'
    'main/git'
    'main/go'
    'main/hurl'
    'main/jq'
    'main/just'
    'main/lazydocker'
    'main/luarocks'
    'main/neofetch'
    'main/nodejs-lts'
    'main/nodejs-lts'
    'main/php'
    'main/pipx'
    'main/ripgrep'
    'main/starship'
    'main/stylua'
    'main/tree-sitter'
    'main/vim'
    'main/xz'
    'main/zig'
    'nerd-fonts/VictorMono-NF-Mono'
    'versions/python311'
)
$buckets.foreach({ scoop bucket add $PSItem })
$packages.foreach({ scoop install $PSItem })
